version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.2.0

executors:
  machine-executor:
    machine:
      enabled: true
    working_directory: ~/repo

jobs:
  checkout_code:
    executor: machine-executor
    steps:
      - checkout

  build_docker_image:
    executor: machine-executor
    steps:
      - checkout
      - gcp-cli/install
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker

      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/llmops-repo/llmops-app:latest .
            docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/llmops-repo/llmops-app:latest

  deploy_to_gke:
    executor: machine-executor
    steps:
      - checkout
      - gcp-cli/install
      - run:
          name: Install latest kubectl locally
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            mv kubectl ~/kubectl
            echo 'export PATH=$HOME:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker

      - run:
          name: Configure GKE
          command: |
            gcloud container clusters get-credentials $GKE_CLUSTER --region $GOOGLE_COMPUTE_REGION --project $GOOGLE_PROJECT_ID

      - run:
          name: Apply Kubernetes Deployment
          command: |
            kubectl apply -f kubernetes-deployment.yaml --validate=false

      - run:
          name: Restart Deployment
          command: |
            kubectl rollout restart deployment/llmops-app

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkout_code
      - build_docker_image:
          requires:
            - checkout_code
      - deploy_to_gke:
          requires:
            - build_docker_image